### ISSUE TITLE
Names are not pronounceable

### ISSUE THREAD

**Issue by DougReeder** [jpwesselink/fbnpj0nifcpjy9x81nw5fnthimudcc2syslkucfrpqiivwizjqc7rgdw2upxre8v#2]
Yeah, I get the joke, but it would be cool (and occasionally useful) if the package names were composed of syllabic elements such as consonant-vowell, consonant-vowell-consonant or vowell.

**Comment by jonaswindey** [comment]
Or something like the names of Heroku instances.

**Comment by jpwesselink** [comment]
Thanks!
